FROM rust:1.69.0-bookworm as builder

COPY src    src
COPY .cargo .cargo
COPY Cargo.toml Cargo.lock .

RUN cargo build --release

FROM debian:bookworm

COPY --from=builder ./target/release/cfnts ./target/release/cfnts
