FROM docker-registry.cfdata.org/stash/plat/dockerfiles/debian-stretch/master:2019.1.0
RUN apt-get update && \
    apt-get -y install memcached python-pip && \
    pip install python-memcached

COPY scripts/ scripts/
CMD ["./scripts/run_memcached.sh"]