version: 2.1
jobs:
  cargo_test:
    docker:
      - image: circleci/rust:1.35.0-stretch
    steps:
      - checkout
      - run:
          name: "Run tests"
          command:
            cargo test
workflows:
  "main":
    jobs:
      - test

